---

env:
  global:
    - CC_TEST_REPORTER_ID=ef448c8e65768d6b4946427451cef2296b83718c572482adbea4b81cd32db2ae

language: node_js
node_js:
  - node
  - 10

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
